spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: IES_DEV
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: IES_DEV
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
server:
  port: 8082
  servlet:
    context-path: /BookStore