INSERT INTO STOCK_PRICE (STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(101,'HCL',700.25);
INSERT INTO STOCK_PRICE (STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(102,'INFOSYS',950.50);
INSERT INTO STOCK_PRICE (STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(103,'BHEL',40.31);
INSERT INTO STOCK_PRICE (STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(104,'IOC',90.10);