server:
  port: 1111
spring:
  application:
    name: CLIENT-ONE
  boot:
    admin:
      client:
        url: http://localhost:9090/
management:
  endpoints:
    web:
      exposure:
        include: '*'