spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    username: IES_DEV
    password: IES_DEV
    url: jdbc:oracle:thin:@locahost:1521/XE
    driver-class-name: oracle.jdbc.driver.OracleDriver

---

spring:
  profiles: qa
  datasource:
    username: IES_QA
    password: IES_QA
    url: jdbc:oracle:thin:@locahost:1521/XE
    driver-class-name: oracle.jdbc.driver.OracleDriver

---

spring:
  profiles: uat
  datasource:
    username: IES_UAT
    password: IES_UAT
    url: jdbc:oracle:thin:@locahost:1521/XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
---

spring:
  profiles: prod
  datasource:
    username: IES_PROD
    password: IES_PROD
    url: jdbc:oracle:thin:@locahost:1521/XE
    driver-class-name: oracle.jdbc.driver.OracleDriver